# Generated by Django 4.2 on 2023-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("stock", models.IntegerField()),
                ("image_url", models.URLField(max_length=7919)),
                ("video_url", models.URLField(blank=True, default="", max_length=7919)),
            ],
        ),
    ]
