# Generated by Django 4.2 on 2023-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_copies_sold_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, default="", max_length=10)),
                ("image_url", models.URLField(max_length=7919)),
                ("products", models.ManyToManyField(blank=True, to="store.product")),
            ],
        ),
    ]
