# Generated by Django 4.2 on 2023-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_cart_alter_product_languages_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.FloatField(),
        ),
    ]
